const strings = {
    en: {
        names: 'Chaewon & Paweł',
        homeNav: 'Home',
        directionsNav: 'Details',
        rsvpNav: 'RSVP',
        title: 'We are getting married!',
        again: 'again',
        joinUs: 'Join us on our special day',
        rsvpButton: 'RSVP Now',
        detailsSection: 'Wedding Details',
        detailsIntro: 'Here is everything you need to know about our special day.',
        dateTitle: 'Date and time',
        date: 'June 10th, 2023',
        time: '4:00 PM',
        ceremony: 'Wedding Ceremony',
        ceremonyText: 'The Sanctuary of Our Lady of Consolation',
        reception: 'Wedding Reception',
        receptionText: 'Pałac na Opieszynie, Września',
        rsvpSection: 'RSVP',
        rsvpText: 'Please let us know if you can make it to our wedding.',
        rsvpName: 'Name:',
        placeholder_rsvpNameText: 'Name',
        rsvpGuests: 'Number of Guests:',
        placeholder_rsvpGuestsText: '',
        message: 'Message:',
        placeholder_messageText: 'Message (optional)',
        value_submit: 'Submit',
        languageNav: 'Language'
    },
    pl: {
        names: 'Chaewon i Paweł',
        homeNav: 'Strona główna',
        directionsNav: 'Szczegóły',
        rsvpNav: 'RSVP',
        title: 'Pobieramy się!',
        again: 'jeszcze raz',
        joinUs: 'Dołącz do nas w naszym wyjątkowym dniu',
        rsvpButton: 'Potwierdź obecność',
        detailsSection: 'Szczegóły ślubu',
        detailsIntro: 'Oto wszystko, co musisz wiedzieć o naszym wyjątkowym dniu.',
        dateTitle: 'Data i godzina',
        date: '10 czerwca 2023',
        time: '16:00',
        ceremony: 'Ceremonia Zaślubin',
        ceremonyText: 'Sanktuarium Matki Bożej Pocieszenia w Biechowie',
        reception: 'Przyjęcie Weselne',
        receptionText: 'Pałac na Opieszynie, Września',
        rsvpSection: 'Potwierdź obecność',
        rsvpText: 'Prosimy o potwierdzenie obecności na naszym ślubie.',
        rsvpName: 'Imię i nazwisko:',
        placeholder_rsvpNameText: 'Imię i nazwisko',
        rsvpGuests: 'Liczba gości:',
        placeholder_rsvpGuestsText: '',
        message: 'Wiadomość:',
        placeholder_messageText: 'Wiadomość (opcjonalnie)',
        value_submit: 'Wyślij',
        languageNav: 'Język'
    },
    kr: {
        names: '채원 & 파벨',
        homeNav: '홈',
        directionsNav: '세부 정보',
        rsvpNav: '참석 확인',
        title: '저희 결혼합니다!',
        again: '다시',
        joinUs: '특별한 날에 함께해주세요',
        rsvpButton: '참석 확인',
        detailsSection: '결혼식 세부 정보',
        detailsIntro: '저희 특별한 날에 대해 알아봅시다.',
        dateTitle: '날짜와 시간',
        date: '2023년 6월 10일',
        time: '오후 4시',
        ceremony: '결혼식',
        ceremonyText: 'Biechowo',
        reception: '리셉션',
        receptionText: 'Pałac na Opieszynie, Września',
        rsvpSection: '참석 확인',
        rsvpText: '저희 결혼식에 참석 여부를 알려주세요.',
        rsvpName: '이름:',
        placeholder_rsvpNameText: '이름',
        rsvpGuests: '참석 인원:',
        placeholder_rsvpGuestsText: '',
        message: '메시지:',
        placeholder_messageText: '메시지 (선택 사항)',
        value_submit: '제출',
        languageNav: '언어'
    }
}